### ISSUE TITLE
NativeAdData cannot be cast back to NativeAd → cannot wrap with NativeAdView for click handling

### ISSUE THREAD

**Issue by long06031999** [LexiLabs-App/basic-ads#100]
Hello, thank you for your perfect library & support NativeAd in v1.0.0-beta04
Currently, 
app.lexilabs.basic:basic-ads:1.0.0-beta04 provides NativeAd support for Compose Multiplatform by exposing a NativeAdData object.

However:

NativeAdData is only intended for UI rendering.

For proper ad click/impression handling, we normally need to wrap the UI in a NativeAdView.(in android)

The problem is that NativeAdData cannot be cast back to the original com.google.android.gms.ads.nativead.NativeAd.

This makes it impossible to correctly wrap the ad UI inside a NativeAdView wrapper, meaning that click and impression tracking cannot be delegated automatically to the SDK.

Expected behavior:
There should be a way to either:

Expose the underlying NativeAd/NativeAdData object along with NativeAdData (or you can return Any for `ad.render()` function and in actual fun NativeAdDefault should be cast manual ), or

Provide a wrapper NativeAdComposable that internally manages the NativeAdView click/impression logic.

Current workaround:
Not possible, since NativeAdData does not provide access to the NativeAd object.

Environment:

Library: app.lexilabs.basic:basic-ads:1.0.0-beta04

Platform: Android (Compose Multiplatform)

Request:
Please consider exposing the original NativeAd or providing an official wrapper that handles NativeAdView automatically.

**Comment by robertjamison** [comment]
I've made some updates that should resolve the issue in version `1.0.0-beta05`.  If you want to test them before release, you can try using the `1.0.0-SNAPSHOT`.

As you mentioned, the root cause was a failure to call `setNativeAd` in the Android and iOS implementations.

**Comment by long06031999** [comment]
Thank you for your hard work.

In beta05, the wrapper issue has been partially fixed — it’s now possible to set the NativeAd for the wrapper successfully.

However, the callToAction view still cannot be set or recognized properly, so click handling for the call-to-action button is not working as expected.
Please refer the [doc](https://github.com/googleads/googleads-mobile-android-examples/blob/main/kotlin/advanced/JetpackComposeDemo/compose-util/src/main/java/com/google/android/gms/compose_util/NativeAdView.kt)

**Comment by long06031999** [comment]
i think it should be like that

`public interface NativeAdUiScope {
    public val nativeAdData: NativeAdData

    @Composable
    public fun NativeAdAdvertiser(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdChoices(modifier: Modifier = Modifier)

    @Composable
    public fun NativeAdMedia(modifier: Modifier = Modifier)

    @Composable
    public fun NativeAdPrice(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdStarRating(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdStore(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdAttribution(modifier: Modifier = Modifier, text: String = "Ad")

    @Composable
    public fun NativeAdHeadline(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdIcon(modifier: Modifier = Modifier)

    @Composable
    public fun NativeAdBody(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})

    @Composable
    public fun NativeAdCallToAction(modifier: Modifier = Modifier, content: @Composable () -> Unit = {})
}`

and we make template like that

`nativeAdTemplate: @Composable NativeAdUiScope.(NativeAdData) -> Unit,`

**Comment by robertjamison** [comment]
If the latest Snapshot publish succeeds tonight, you should have a prototype of the new framework to play with.  It was much more complicated than I expected.

**Comment by long06031999** [comment]
Does this version have full ios support? @robertjamison

**Comment by robertjamison** [comment]
I wasn't able to fully test it tonight, but theoretically it should at least display the content.  I'm not sure if I got the content clicks to register with the `eventListener` yet.

I'm guessing the GitHub Action publishing the snapshot will finish in 30 minutes.

**Comment by long06031999** [comment]
@robertjamison 
I saw the snapshots but how do I use them?

NativeAd(
activity = context,
nativeAdTemplate =???
)
how to define or using NativeAdDefault in common main
